Fix version replacement workflow for pre-release (#285)
### Issue

When the new version has a qualifier, the current version replacement
breaks badge URLs. In badges, '-' characters must be "escaped" as '--'.

Replace of '2024.1.1' for '2024.2.0-alpha01' (#280):

- Expected:
https://img.shields.io/badge/Maven%20Central-2024.2.0--alpha01-blue
- Actual:
https://img.shields.io/badge/Maven%20Central-2024.2.0-alpha01-blue

Caused `main` check to fail:

```
ERROR: 2 dead links found!
[✖] https://img.shields.io/badge/Maven%20Central-2024.2.0-alpha01-blue → Status: 404
[✖] https://img.shields.io/badge/Javadoc-2024.2.0-alpha01-orange → Status: 404
```


https://github.com/gabrielfeo/develocity-api-kotlin/actions/runs/10705233856/job/29680113989

### Fix

Add more test scenarios. Fix replacement of versions inside badge URLs,
according to tests.