Update Kotlin/Jupyter to v0.12.0-356 (#349)
Fixes an error that's failing the Jupyter integration tests, encountered
while testing #346:

```
org.jetbrains.kotlinx.jupyter.exceptions.ReplLibraryException: The problem is found in one of the loaded libraries: check library imports, dependencies and repositories
	at app//org.jetbrains.kotlinx.jupyter.exceptions.ReplLibraryExceptionKt.rethrowAsLibraryException(ReplLibraryException.kt:38)
	at app//org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.doAddLibraries(CellExecutorImpl.kt:158)
	at app//org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$ExecutionContext.addLibraries(CellExecutorImpl.kt:193)
	at app//org.jetbrains.kotlinx.jupyter.libraries.LibrariesScanner.addLibrariesFromClassLoader(LibrariesScanner.kt:66)
	at app//org.jetbrains.kotlinx.jupyter.libraries.LibrariesScanner.addLibrariesFromClassLoader$default(LibrariesScanner.kt:55)
	at app//org.jetbrains.kotlinx.jupyter.testkit.ReplProvider$Companion$initializeWithCurrentClasspath$1.invoke(ReplProvider.kt:58)
	at app//org.jetbrains.kotlinx.jupyter.testkit.ReplProvider$Companion$initializeWithCurrentClasspath$1.invoke(ReplProvider.kt:58)
	at app//org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute(CellExecutorImpl.kt:136)
	at app//org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl$eval$1.invoke(ReplForJupyterImpl.kt:625)
	at app//org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.withEvalContext(ReplForJupyterImpl.kt:427)
	at app//org.jetbrains.kotlinx.jupyter.repl.impl.ReplForJupyterImpl.eval(ReplForJupyterImpl.kt:624)
	at app//org.jetbrains.kotlinx.jupyter.testkit.ReplProvider$Companion.initializeWithCurrentClasspath(ReplProvider.kt:58)
	at app//org.jetbrains.kotlinx.jupyter.testkit.ReplProvider$Companion.withoutLibraryResolution$lambda$1(ReplProvider.kt:23)
	at app//org.jetbrains.kotlinx.jupyter.testkit.JupyterReplTestCase.<init>(JupyterReplTestCase.kt:17)
	at app//org.jetbrains.kotlinx.jupyter.testkit.JupyterReplTestCase.<init>(JupyterReplTestCase.kt:14)
	at app//com.gabrielfeo.develocity.api.internal.jupyter.DevelocityApiJupyterIntegrationTest.<init>(DevelocityApiJupyterIntegrationTest.kt:12)
	at java.base@11.0.25/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base@11.0.25/java.util.Optional.orElseGet(Optional.java:369)
	at java.base@11.0.25/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base@11.0.25/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: org.jetbrains.kotlinx.jupyter.exceptions.ReplCompilerException: Collection contains no element matching the predicate.
	...
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	...
```

([/s/](https://gradle.com/s/rujr57kbibywg))

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>