Bump org.jetbrains.kotlin.jvm from 1.8.22 to 1.9.0 (#96)
Bumps [org.jetbrains.kotlin.jvm](https://github.com/JetBrains/kotlin)
from 1.8.22 to 1.9.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/releases">org.jetbrains.kotlin.jvm's
releases</a>.</em></p>
<blockquote>
<h2>Kotlin 1.9.0</h2>
<h2>Changelog</h2>
<h3>Analysis API</h3>
<h4>New Features</h4>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57930"><code>KT-57930</code></a>
Analysis API: provide an API for extending Kotlin resolution</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57636"><code>KT-57636</code></a>
K2: Add the return type of K2 reference shortener AA
<code>ShortenCommand::invokeShortening()</code> e.g.,
<code>ShorteningResultInfo</code> to allow callers to access the
shortening result PSI</li>
</ul>
<h4>Fixes</h4>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-58249"><code>KT-58249</code></a>
Analysis API: Disable error logging for FE10 implementation of
resolveCall when resolve is not successful</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-55626"><code>KT-55626</code></a>
Impossible to restore symbol by psi from script file</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57314"><code>KT-57314</code></a>
LL FIR: Combine <code>LLFirProvider$SymbolProvider</code>s in session
dependencies (optimization)</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-55527"><code>KT-55527</code></a>
K2 IDE: Rewrite KtScopeContext class to allow to handle each scope
separately</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-55329"><code>KT-55329</code></a>
LL FIR: Unexpected ACTUAL_WITHOUT_EXPECT error on constructor and
function declaration</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-50732"><code>KT-50732</code></a>
LL API: fix compiler based tests</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57850"><code>KT-57850</code></a>
K2: contract violation due to
SymbolLightAccessorMethod.propertyAccessorSymbol</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56543"><code>KT-56543</code></a>
LL FIR: rework lazy transformers so transformers modify only
declarations they suppose to</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56721"><code>KT-56721</code></a>
K2: FirExtensionDeclarationsSymbolProvider:
java.lang.IllegalStateException: Recursive update</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-50253"><code>KT-50253</code></a>
Analysis API: Solve issues with ProcessCancelledException</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56800"><code>KT-56800</code></a>
K2 IDE: optimize deprecation calculation for symbols</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-55006"><code>KT-55006</code></a>
Analysis API does not transform Java type refs for callable symbol
return types</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57256"><code>KT-57256</code></a>
AA FIR: Reduce lazy resolve phase for deprecation status</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57619"><code>KT-57619</code></a>
K2: CFG for class initializer is not correctly built in reversed resolve
mode</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-58141"><code>KT-58141</code></a>
K2: AA FIR: impossible to restore symbol for declaration with annotation
with argument inside type</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57462"><code>KT-57462</code></a>
Symbol Light Classes: SymbolLightFieldForProperty should retrieve
annotations not from KtPropertySymbol, but from the corresponding
backing field</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54864"><code>KT-54864</code></a>
Analysis API: add function to get expect KtSymbol list by actual
KtSymbol</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56763"><code>KT-56763</code></a>
Analysis API: <code>.KtSourceModuleImpl is missing in the map.</code> on
symbol restore when symbol cannot be seen from the use-site module</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56617"><code>KT-56617</code></a>
Analysis API: optimize
KtFirSymbolProviderByJavaPsi.getNamedClassSymbol</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54430"><code>KT-54430</code></a>
K2: .getAllOverriddenSymbols() returns invalid results</li>
</ul>
<h3>Backend. Native. Debug</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-55440"><code>KT-55440</code></a>
Kotlin/Native debugger: inline function parameters are not visible
during debugging</li>
</ul>
<h3>Backend. Wasm</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-58293"><code>KT-58293</code></a>
Wasm: ReferenceError: e is not defined in kotlin.test.jsThrow</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-58931"><code>KT-58931</code></a>
Wasm tests are failing to start on Kotlin 1.9.0-Beta</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-58188"><code>KT-58188</code></a>
Restore binary compatibility of
PlatformDiagnosticSuppressor.shouldReportUnusedParameter</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57136"><code>KT-57136</code></a>
K/Wasm: Restrict non-external types in JS interop</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57060"><code>KT-57060</code></a>
Clarify the lack of support for dynamic in Kotlin/Wasm</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56955"><code>KT-56955</code></a>
K/Wasm: Support restricted version of K/JS <code>js(code)</code></li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57276"><code>KT-57276</code></a>
Wasm: &quot;Body not found for function&quot; error when compiling
konform library with Kotlin/Wasm support</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-56976"><code>KT-56976</code></a>
K/Wasm bug with calling override of external function with default
parameters</li>
</ul>
<h3>Compiler</h3>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md">org.jetbrains.kotlin.jvm's
changelog</a>.</em></p>
<blockquote>
<h2>1.8.21</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57848"><code>KT-57848</code></a>
Native: compilation of dynamic/static library fails with Xcode 14.3</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57875"><code>KT-57875</code></a>
Native compilation failure: Suspend functions should be lowered out at
this point, but FUN LOCAL_FUNCTION_FOR_LAMBDA</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57946"><code>KT-57946</code></a>
KAPT: &quot;RuntimeException: No type for expression&quot; with
delegate</li>
</ul>
<h3>JavaScript</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57356"><code>KT-57356</code></a>
KJS: StackOverflowException on <a
href="https://github.com/JsExport"><code>@​JsExport</code></a> with type
parameters referring to one another</li>
</ul>
<h3>Tools. Compiler plugins. Serialization</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-58067"><code>KT-58067</code></a>
Serialization: NullPointerException caused by <a
href="https://github.com/Contextual"><code>@​Contextual</code></a>
property with type with generic</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57730"><code>KT-57730</code></a>
Serialization: &quot;IllegalStateException: Serializer for element of
type <!-- raw HTML omitted -->.Foo has not been found&quot; caused by
serialization of Java type</li>
</ul>
<h3>Tools. Gradle. JS</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-57766"><code>KT-57766</code></a>
KJS / Gradle &quot;Module not found: Error: Can't resolve
'kotlin-kotlin-stdlib-js-ir'&quot; when using
&quot;useEsModules&quot;</li>
</ul>
<h3>Tools. Kapt</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-58027"><code>KT-58027</code></a>
Kotlin 1.8.20 kapt issue &quot;null: KtCallExpression:
build()&quot;</li>
</ul>
<h3>Tools. Maven</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-58048"><code>KT-58048</code></a>
Maven: &quot;Too many source module declarations found&quot; after
upgrading to 1.8.20</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-58101"><code>KT-58101</code></a>
'Unable to access class' in kotlin-maven-plugin after updating to Kotlin
1.8.20</li>
</ul>
<h2>1.8.20</h2>
<h3>Analysis API</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-55510"><code>KT-55510</code></a>
K2: Lost designation for local classes</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-55191"><code>KT-55191</code></a>
AA: add an API to compare symbol pointers</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-55487"><code>KT-55487</code></a>
K2: symbol pointer restoring doesn't work for static members</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-55336"><code>KT-55336</code></a>
K2 IDE: &quot;java.lang.IllegalStateException: Required value was
null.&quot; exception while importing a compiled JPS project</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-55098"><code>KT-55098</code></a>
AA: KtDeclarationRenderer should render a context receivers</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-51181"><code>KT-51181</code></a>
LL API: errors for SAM with suspend function from another module</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-50250"><code>KT-50250</code></a>
Analysis API: Implement Analysis API of
KtExpression.isUsedAsExpression</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-54360"><code>KT-54360</code></a>
KtPropertySymbol: support JvmField in javaSetterName and
javaGetterName</li>
</ul>
<h3>Analysis API. FE1.0</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-55825"><code>KT-55825</code></a>
AA FE1.0: stackoverflow when resolution to a function with a recursive
type parameter</li>
</ul>
<h3>Analysis API. FIR</h3>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/JetBrains/kotlin/commit/bcf27812cd28041e0b9ffa3bfe52fc58c397d0eb"><code>bcf2781</code></a>
Add ChangeLog for 1.9.0</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/d372470550a63c9b7f0a5046830ad6bc633c6ff1"><code>d372470</code></a>
Don't get BuildScanExtension when buildScan report is disabled</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/0ec76786a66598a82463614cf239394133352710"><code>0ec7678</code></a>
[Gradle, JS] Return back deprecated methods for compatibility</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/2427b51ba8b0b2f5db1a195f2b5d800ff10a853a"><code>2427b51</code></a>
Relocate aalto-xml and stax2-api dependencies in embeddable compiler
(KT-59631)</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/56a7789f1dc72f8bf840f99a8964a7ddff1ee5ee"><code>56a7789</code></a>
Revert &quot;[Gradle] Fix invalidating iOS framework after
import&quot;</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/8cf1abc2947ce3de06d04fbd19c1af657034ba36"><code>8cf1abc</code></a>
Add the possibility to omit explicitly specifying a version in
annotationProc...</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/4823fc3c64de9a1c9d9a240f4c2bbd648c00b2e4"><code>4823fc3</code></a>
[Gradle] GranularMetadataTransformation: Collect moduleIds in
ProjectData for...</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/0d1932eab67ea257aa41ded7a112cebbeaecba78"><code>0d1932e</code></a>
[Gradle] Implement Future&lt;T&gt;.map(transform)</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/bbf64b14d7ede0da1583a769455850b34f86f23b"><code>bbf64b1</code></a>
[Gradle] Implement
KT59446TransformationOnTransitiveJavaDependencyTest</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/54b11e3a955b0811bad248660e7a6587c1e593cb"><code>54b11e3</code></a>
[Gradle] KotlinPluginLifecycle: Implement .toString for better
diagnostics</li>
<li>Additional commits viewable in <a
href="https://github.com/JetBrains/kotlin/compare/v1.8.22...v1.9.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.kotlin.jvm&package-manager=gradle&previous-version=1.8.22&new-version=1.9.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually


</details>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Gabriel Feo <gabriel@gabrielfeo.com>