Fix token reading in Linux (#56)
Closes #54 

### #54

Trying to use it in Linux with `GRADLE_ENTERPRISE_API_TOKEN` fails first
due to having no `LOGNAME` variable:

```
null
java.lang.NullPointerException
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1090)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.gabrielfeo.gradle.enterprise.api.internal.RealKeychain.get(Keychain.kt:18)
	at com.gabrielfeo.gradle.enterprise.api.Options$GradleEnterpriseInstanceOptions$token$1.invoke(Options.kt:56)
	at com.gabrielfeo.gradle.enterprise.api.Options$GradleEnterpriseInstanceOptions$token$1.invoke(Options.kt:55)
	at com.gabrielfeo.gradle.enterprise.api.internal.OkHttpClientKt.addNetworkInterceptors(OkHttpClient.kt:49)
	at com.gabrielfeo.gradle.enterprise.api.internal.OkHttpClientKt.buildOkHttpClient(OkHttpClient.kt:27)
	at com.gabrielfeo.gradle.enterprise.api.internal.OkHttpClientKt$okHttpClient$2.invoke(OkHttpClient.kt:16)
	at com.gabrielfeo.gradle.enterprise.api.internal.OkHttpClientKt$okHttpClient$2.invoke(OkHttpClient.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.gabrielfeo.gradle.enterprise.api.internal.OkHttpClientKt.getOkHttpClient(OkHttpClient.kt:15)
	at com.gabrielfeo.gradle.enterprise.api.internal.RetrofitKt$retrofit$2.invoke(Retrofit.kt:15)
	at com.gabrielfeo.gradle.enterprise.api.internal.RetrofitKt$retrofit$2.invoke(Retrofit.kt:12)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.gabrielfeo.gradle.enterprise.api.internal.RetrofitKt.getRetrofit(Retrofit.kt:12)
	at com.gabrielfeo.gradle.enterprise.api.ApiKt$gradleEnterpriseApi$2.invoke(Api.kt:11)
	at com.gabrielfeo.gradle.enterprise.api.ApiKt$gradleEnterpriseApi$2.invoke(Api.kt:10)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.gabrielfeo.gradle.enterprise.api.ApiKt.getGradleEnterpriseApi(Api.kt:10)
```

After setting a dummy `LOGNAME`, it'll still fail because ProcessBuilder
throws an `IOException` for command not found, instead of just setting
status to 127:

```
Cannot run program "security": error=2, No such file or directory
java.io.IOException: Cannot run program "security": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.gabrielfeo.gradle.enterprise.api.internal.RealKeychain.get(Keychain.kt:18)
	at com.gabrielfeo.gradle.enterprise.api.Options$GradleEnterpriseInstanceOptions$token$1.invoke(Options.kt:56)
	at com.gabrielfeo.gradle.enterprise.api.Options$GradleEnterpriseInstanceOptions$token$1.invoke(Options.kt:55)
	at com.gabrielfeo.gradle.enterprise.api.internal.OkHttpClientKt.addNetworkInterceptors(OkHttpClient.kt:49)
	at com.gabrielfeo.gradle.enterprise.api.internal.OkHttpClientKt.buildOkHttpClient(OkHttpClient.kt:27)
	at com.gabrielfeo.gradle.enterprise.api.internal.OkHttpClientKt$okHttpClient$2.invoke(OkHttpClient.kt:16)
	at com.gabrielfeo.gradle.enterprise.api.internal.OkHttpClientKt$okHttpClient$2.invoke(OkHttpClient.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.gabrielfeo.gradle.enterprise.api.internal.OkHttpClientKt.getOkHttpClient(OkHttpClient.kt:15)
	at com.gabrielfeo.gradle.enterprise.api.internal.RetrofitKt$retrofit$2.invoke(Retrofit.kt:15)
	at com.gabrielfeo.gradle.enterprise.api.internal.RetrofitKt$retrofit$2.invoke(Retrofit.kt:12)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.gabrielfeo.gradle.enterprise.api.internal.RetrofitKt.getRetrofit(Retrofit.kt:12)
	at com.gabrielfeo.gradle.enterprise.api.ApiKt$gradleEnterpriseApi$2.invoke(Api.kt:11)
	at com.gabrielfeo.gradle.enterprise.api.ApiKt$gradleEnterpriseApi$2.invoke(Api.kt:10)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.gabrielfeo.gradle.enterprise.api.ApiKt.getGradleEnterpriseApi(Api.kt:10)
```